INSERT INTO ingredients (id, name, type, measurement_unit, serving_quantity, created_at, updated_at) VALUES
(1, 'Salt', 'spice', 'grams', 1, NOW(), NOW()),
(2, 'Pepper', 'spice', 'grams', 1, NOW(), NOW()),
(3, 'Olive Oil', 'oil', 'milliliters', 10, NOW(), NOW()),
(4, 'Garlic', 'vegetable', 'clove', 1, NOW(), NOW()),
(5, 'Onion', 'vegetable', 'grams', 100, NOW(), NOW()),
(6, 'Tomato', 'fruit', 'grams', 150, NOW(), NOW()),
(7, 'Chicken Breast', 'meat', 'grams', 200, NOW(), NOW()),
(8, 'Rice', 'grain', 'grams', 100, NOW(), NOW()),
(9, 'Broccoli', 'vegetable', 'grams', 50, NOW(), NOW()),
(10, 'Cheese', 'dairy', 'grams', 30, NOW(), NOW());
INSERT INTO ingredients (id, name, type, measurement_unit, serving_quantity, created_at, updated_at) VALUES
(11, 'Eggs', 'dairy', 'unit', 2, NOW(), NOW()),
(12, 'Butter', 'dairy', 'grams', 20, NOW(), NOW()),
(13, 'Flour', 'grain', 'grams', 200, NOW(), NOW()),
(14, 'Sugar', 'sweetener', 'grams', 50, NOW(), NOW()),
(15, 'Basil', 'herb', 'grams', 5, NOW(), NOW()),
(16, 'Lemon Juice', 'liquid', 'milliliters', 15, NOW(), NOW()),
(17, 'Soy Sauce', 'condiment', 'milliliters', 20, NOW(), NOW()),
(18, 'Honey', 'sweetener', 'grams', 30, NOW(), NOW()),
(19, 'Cumin Powder', 'spice', 'grams', 3, NOW(), NOW()),
(20, 'Paprika', 'spice', 'grams', 2, NOW(), NOW());
INSERT INTO ingredients (id, name, type, measurement_unit, serving_quantity, created_at, updated_at) VALUES
(21, 'Cilantro', 'herb', 'grams', 5, NOW(), NOW()),
(22, 'Lettuce', 'vegetable', 'grams', 50, NOW(), NOW()),
(23, 'Bell Pepper', 'vegetable', 'grams', 100, NOW(), NOW()),
(24, 'Ground Beef', 'meat', 'grams', 250, NOW(), NOW()),
(25, 'Pasta', 'grain', 'grams', 150, NOW(), NOW()),
(26, 'Yogurt', 'dairy', 'grams', 100, NOW(), NOW()),
(27, 'Apple', 'fruit', 'grams', 200, NOW(), NOW()),
(28, 'Banana', 'fruit', 'grams', 120, NOW(), NOW()),
(29, 'Cucumber', 'vegetable', 'grams', 80, NOW(), NOW()),
(30, 'Potato', 'vegetable', 'grams', 150, NOW(), NOW());
INSERT INTO ingredients (id, name, type, measurement_unit, serving_quantity, created_at, updated_at) VALUES
(31, 'Pork Chop', 'meat', 'grams', 300, NOW(), NOW()),
(32, 'Salmon', 'fish', 'grams', 200, NOW(), NOW()),
(33, 'Shrimp', 'seafood', 'grams', 150, NOW(), NOW()),
(34, 'Bread', 'grain', 'grams', 100, NOW(), NOW()),
(35, 'Rice Vinegar', 'condiment', 'milliliters', 10, NOW(), NOW()),
(36, 'Sesame Oil', 'oil', 'milliliters', 5, NOW(), NOW()),
(37, 'Chili Flakes', 'spice', 'grams', 1, NOW(), NOW()),
(38, 'Black Beans', 'legume', 'grams', 200, NOW(), NOW()),
(39, 'Corn Kernels', 'vegetable', 'grams', 100, NOW(), NOW()),
(40, 'Green Beans', 'vegetable', 'grams', 80, NOW(), NOW());
INSERT INTO ingredients (id, name, type, measurement_unit, serving_quantity, created_at, updated_at) VALUES
(41, 'Zucchini', 'vegetable', 'grams', 100, NOW(), NOW()),
(42, 'Spinach', 'vegetable', 'grams', 50, NOW(), NOW()),
(43, 'Mushrooms', 'fungi', 'grams', 100, NOW(), NOW()),
(44, 'Almonds', 'nut', 'grams', 30, NOW(), NOW()),
(45, 'Walnuts', 'nut', 'grams', 30, NOW(), NOW()),
(46, 'Peanut Butter', 'nut', 'grams', 20, NOW(), NOW()),
(47, 'Coconut Milk', 'liquid', 'milliliters', 200, NOW(), NOW()),
(48, 'Oats', 'grain', 'grams', 50, NOW(), NOW()),
(49, 'Chickpeas', 'legume', 'grams', 150, NOW(), NOW()),
(50, 'Lentils', 'legume', 'grams', 150, NOW(), NOW())
(51, 'Beef', 'red meat', 'grams', 250, NOW(), NOW()),
(52, 'Pork', 'red meat', 'grams', 250, NOW(), NOW()),
(53, 'Turkey', 'poultry', 'grams', 200, NOW(), NOW()),
(54, 'Duck', 'poultry', 'grams', 200, NOW(), NOW()),
(56, 'Crab', 'seafood', 'grams', 150, NOW(), NOW()),
(57, 'Lobster', 'seafood', 'grams', 150, NOW(), NOW()),
(58, 'Tuna', 'fish', 'grams', 200, NOW(), NOW()),
(59, 'Sardines', 'fish', 'grams', 150, NOW(), NOW()),
(60, 'Anchovies', 'fish', 'grams', 100, NOW(), NOW());