INSERT INTO measurements (name, unit, abbreviation, type, teaspoon_equivalent) VALUES
('Teaspoon', 'teaspoon', 'tsp', 'volume', 1),
('Tablespoon', 'tablespoon', 'tbsp', 'volume', 3),
('Cup', 'cup', 'cup', 'volume', 48),
('Fluid Ounce', 'fluid ounce', 'fl oz', 'volume', 6),
('Pint', 'pint', 'pt', 'volume', 96),
('Quart', 'quart', 'qt', 'volume', 192),
('Gallon', 'gallon', 'gal', 'volume', 768),
('Milliliter', 'milliliter', 'ml', 'volume', 0.2),
('Liter', 'liter', 'l', 'volume', 202.884),
('Pinch', 'pinch', 'pinch', 'volume', 0.1667),
('Dash', 'dash', 'dash', 'volume', 0.0833),
('Cubic Centimeter', 'cubic centimeter', 'cc', 'volume', 0.2),
('Cubic Meter', 'cubic meter', 'm³', 'volume', 202884),
('Milligram', 'milligram', 'mg', 'weight', null),
('Gram', 'gram', 'g', 'weight', null),
('Kilogram', 'kilogram', 'kg', 'weight', null),
('Ounce', 'ounce', 'oz', 'weight', null),
('Pound', 'pound', 'lb', 'weight', null),
('Unit', 'unit', 'unit', 'count', null),
('Piece', 'piece', 'pc', 'count', null),
('Slice', 'slice', 'slice', 'count', null),
('Clove', 'clove', 'clove', 'count', null),
('Head', 'head', 'head', 'count', null),
('Bunch', 'bunch', 'bunch', 'count', null),
('Sprig', 'sprig', 'sprig', 'count', null),
('Leaf', 'leaf', 'leaf', 'count', null)
('Big', 'big', 'big', 'size', null),
('Medium', 'medium', 'medium', 'size', null),
('Small', 'small', 'small', 'size', null)
;
